# This is a basic workflow to help you get started with Actions

name: Linux Wheel

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build manylinux wheels x86_64
        run: |
          python --version
          python -m pip install --disable-pip-version-check --upgrade pip
          pip install -U -r requirements.txt -r requirements-dev.txt
          python --version
          python -c "import numpy; print('numpy %s' % numpy.__version__)"
          # Source distribution
          python setup.py sdist
          # Built distribution (wheel)
          python setup.py bdist_wheel --plat-name x86_64
          # Install locally to support tests
          pip install -e .
          for whl in dist/*$(python -c "import wheel.pep425tags as w; print(w.get_platform())").whl; do
              auditwheel repair $whl -w ./dist/
              rm $whl
          done
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl
