name: Linux Build and Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheel_x86_64:
    name: "Build x86_64 ${{ matrix.pyver }}"
    strategy:
      matrix:
        pyver: ['3.6', '3.7', '3.8', '3.9']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install dependencies
        run: |
          python -m pip install --disable-pip-version-check --upgrade pip
          pip install -U -r requirements.txt -r requirements-dev.txt
          pip install auditwheel
          #Install locally to support tests
          pip install -e .
      - name: Building source distribution
        run: python setup.py sdist     
      - name: Building wheel
        run: python setup.py bdist_wheel
      - name: Repair wheel
        run: auditwheel repair dist/*.whl --wheel-dir wheelhouse --plat linux_x86_64
          #for whl in dist/*$(python -c "import wheel.pep425tags as w; print(w.get_platform())").whl; do
           #   auditwheel repair $whl -w ./dist/ --plat linux_x86_64
            #  rm $whl
          #done
      - name: Test with pytest
        run: pytest      
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl
  build_wheel_aarch64:
    name: "Build aarch64 ${{ matrix.pyver }}"
    strategy:
      matrix:
        pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
         docker run --rm --privileged hypriot/qemu-register
    - uses: docker://quay.io/pypa/manylinux2014_aarch64
      with:
        args: |
            bash -c "${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
            source .env/bin/activate && \
            if \[ ${{ matrix.pyver }} == cp36-cp36m \] ; then
              pip install --upgrade setuptools
            fi && \
            python -m pip install --disable-pip-version-check --upgrade pip && \
            pip install -U -r requirements.txt -r requirements-dev.txt && \
            python setup.py bdist_wheel && \
            pip install -e . && \
            auditwheel repair dist/*.whl --wheel-dir wheelhouse && \
            #--plat linux_aarch64
            pytest && \
            deactivate"
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
